# Generated by MultiServer — do not edit.
import os
import sys
from pathlib import Path

_root = Path(__file__).resolve().parent.parent
os.chdir(_root)
if str(_root) not in sys.path:
    sys.path.insert(0, str(_root))

from app import app  # noqa: E402

_prefix = os.environ.get('MULTISERVER_SCRIPT_NAME', '').strip().rstrip('/')
if _prefix:
    class _ScriptNameMiddleware:
        def __init__(self, wsgi_app, script_name):
            self.wsgi_app = wsgi_app
            self.script_name = script_name

        def __call__(self, environ, start_response):
            environ['SCRIPT_NAME'] = self.script_name
            return self.wsgi_app(environ, start_response)

    app.wsgi_app = _ScriptNameMiddleware(app.wsgi_app, _prefix)

if __name__ == '__main__':
    _port = int(os.environ.get('PORT', '5000'))
    app.run(host='0.0.0.0', port=_port, debug=False, use_reloader=False)
