#!/usr/bin/env python3
"""
setup_secrets.py — First-time secrets setup for Restaurant System
================================================================
Generates a .env file from env.template with a secure SECRET_KEY.

Run once on each new installation:
    python setup_secrets.py

Safe to re-run: will not overwrite an existing .env unless you confirm.
"""

import os
import secrets
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TEMPLATE_PATH = os.path.join(HERE, 'env.template')
ENV_PATH = os.path.join(HERE, '.env')
PLACEHOLDER = 'CHANGE-THIS-TO-A-SECURE-RANDOM-HEX-STRING'


def generate_secret_key() -> str:
    return secrets.token_hex(32)


def load_template() -> str:
    if not os.path.exists(TEMPLATE_PATH):
        print(f"ERROR: env.template not found at {TEMPLATE_PATH}")
        sys.exit(1)
    with open(TEMPLATE_PATH, 'r') as f:
        return f.read()


def write_env(content: str) -> None:
    with open(ENV_PATH, 'w') as f:
        f.write(content)


def main():
    print("=" * 60)
    print("  Restaurant System — Secrets Setup")
    print("=" * 60)

    # --- Guard: don't silently overwrite an existing .env ---
    if os.path.exists(ENV_PATH):
        print(f"\nWARNING: A .env file already exists at:\n  {ENV_PATH}\n")
        answer = input("Overwrite it? This will generate a NEW SECRET_KEY. [y/N] ").strip().lower()
        if answer != 'y':
            print("Aborted. Existing .env was not changed.")
            sys.exit(0)
        print()

    # --- Generate values ---
    secret_key = generate_secret_key()
    print(f"Generated SECRET_KEY: {secret_key[:8]}...{secret_key[-8:]}  (64 hex chars)")

    # --- Build .env from template ---
    template = load_template()
    env_content = template.replace(PLACEHOLDER, secret_key)

    # Add a header note that this file was generated (not hand-edited)
    header = (
        "# ============================================================\n"
        "#  Restaurant System — Environment Secrets\n"
        "#  DO NOT commit this file to version control.\n"
        "#  Each installation should have its own unique values.\n"
        "#  Generated by setup_secrets.py\n"
        "# ============================================================\n\n"
    )
    # Remove the block-comment header already in the template to avoid duplication
    lines = env_content.splitlines(keepends=True)
    stripped = []
    in_header = True
    for line in lines:
        if in_header and (line.startswith('#') or line.strip() == ''):
            continue
        in_header = False
        stripped.append(line)
    env_content = header + ''.join(stripped)

    write_env(env_content)
    print(f"\n.env written to:\n  {ENV_PATH}\n")
    print("Next steps:")
    print("  1. Review .env and adjust HOST/PORT if needed.")
    print("  2. Start the system with:  run_production.bat")
    print("  3. Keep .env off version control (it is in .gitignore).")
    print()


if __name__ == '__main__':
    main()
