"""Cross-platform command helpers (Windows PATH / npm.cmd fixes)."""

from __future__ import annotations

import json
import os
import re
import shutil
import sys
from pathlib import Path


def find_npm() -> str | None:
    for name in ("npm.cmd", "npm.exe", "npm"):
        found = shutil.which(name)
        if found:
            return found
    return None


def npm_command(*args: str) -> list[str]:
    """
    Build argv to run npm on Windows (avoids WinError 2 when npm is not directly executable).
    """
    if sys.platform == "win32":
        return ["cmd", "/c", "npm", *args]
    npm = find_npm() or "npm"
    return [npm, *args]


def write_nextjs_dev_launcher(project_dir: Path, port: int) -> Path:
    """Next.js with source (next dev) — e.g. E:\\AutoM.System src tree."""
    project_dir = project_dir.resolve()
    ms_dir = project_dir / ".multiserver"
    ms_dir.mkdir(exist_ok=True)
    launch = ms_dir / "launch.bat"
    launch.write_text(
        f"@echo off\r\n"
        f'cd /d "{project_dir}"\r\n'
        f"set PORT={port}\r\n"
        f"set BROWSER=none\r\n"
        f"call npm run dev -- -p {port}\r\n",
        encoding="utf-8",
    )
    return launch


def write_nextjs_dist_launcher(project_dir: Path, port: int) -> Path:
    """Compiled distribution (next start) — deploy / distributions folders."""
    project_dir = project_dir.resolve()
    ms_dir = project_dir / ".multiserver"
    ms_dir.mkdir(exist_ok=True)
    launch = ms_dir / "launch.bat"
    launch.write_text(
        f"@echo off\r\n"
        f'cd /d "{project_dir}"\r\n'
        f"set PORT={port}\r\n"
        f"set NODE_ENV=production\r\n"
        f"set BROWSER=none\r\n"
        f"if not exist .env.local if exist .env.example copy /Y .env.example .env.local >nul\r\n"
        f"call npm run start -- -p {port}\r\n",
        encoding="utf-8",
    )
    return launch


def write_flask_launcher(project_dir: Path, port: int, script_name: str = "") -> Path:
    """
    Flask apps on Windows (emoji logs, cp1252).
    Uses `flask run --port` so apps with hardcoded app.run(port=5000) still bind correctly.
    When script_name is set (e.g. /demo/repair-restaurant), writes a WSGI entry so
    url_for() links work behind the public /demo/<slug>/ path.
    """
    project_dir = project_dir.resolve()
    ms_dir = project_dir / ".multiserver"
    ms_dir.mkdir(exist_ok=True)
    launch = ms_dir / "launch.bat"
    entry = ms_dir / "entry.py"
    prefix = (script_name or "").strip().rstrip("/")
    entry.write_text(
        "# Generated by MultiServer — do not edit.\n"
        "import os\n"
        "import sys\n"
        "from pathlib import Path\n"
        "\n"
        "_root = Path(__file__).resolve().parent.parent\n"
        "os.chdir(_root)\n"
        "if str(_root) not in sys.path:\n"
        "    sys.path.insert(0, str(_root))\n"
        "\n"
        "from app import app  # noqa: E402\n"
        "\n"
        "_prefix = os.environ.get('MULTISERVER_SCRIPT_NAME', '').strip().rstrip('/')\n"
        "if _prefix:\n"
        "    class _ScriptNameMiddleware:\n"
        "        def __init__(self, wsgi_app, script_name):\n"
        "            self.wsgi_app = wsgi_app\n"
        "            self.script_name = script_name\n"
        "\n"
        "        def __call__(self, environ, start_response):\n"
        "            environ['SCRIPT_NAME'] = self.script_name\n"
        "            return self.wsgi_app(environ, start_response)\n"
        "\n"
        "    app.wsgi_app = _ScriptNameMiddleware(app.wsgi_app, _prefix)\n"
        "\n"
        "if __name__ == '__main__':\n"
        "    _port = int(os.environ.get('PORT', '5000'))\n"
        "    app.run(host='0.0.0.0', port=_port, debug=False, use_reloader=False)\n",
        encoding="utf-8",
    )
    script_env = f"set MULTISERVER_SCRIPT_NAME={prefix}\r\n" if prefix else ""
    launch.write_text(
        f"@echo off\r\n"
        f"chcp 65001 >nul\r\n"
        f'cd /d "{project_dir}"\r\n'
        f"set PYTHONUTF8=1\r\n"
        f"set PYTHONIOENCODING=utf-8\r\n"
        f"set PORT={port}\r\n"
        f"{script_env}"
        f"if not exist .env (\r\n"
        f"  if exist setup_secrets.py (\r\n"
        f"    echo [MultiServer] No .env found — running setup_secrets.py...\r\n"
        f"    call python setup_secrets.py\r\n"
        f"    if errorlevel 1 exit /b 1\r\n"
        f"  )\r\n"
        f")\r\n"
        f"set FLASK_APP=.multiserver\\entry\r\n"
        f"set DEV_MODE=1\r\n"
        f"set FLASK_ENV=development\r\n"
        f"set BROWSER=none\r\n"
        f"call python -X utf8 -m flask run --host 0.0.0.0 --port {port} --no-reload\r\n"
        f"if errorlevel 1 (\r\n"
        f"  echo Flask CLI failed, trying entry.py fallback>>\"%TEMP%\\multiserver-flask.log\"\r\n"
        f"  call python -X utf8 .multiserver\\entry.py\r\n"
        f")\r\n",
        encoding="utf-8",
    )
    return launch


def write_nextjs_launcher(project_dir: Path, port: int) -> Path:
    """Backward-compatible alias — picks dev vs dist automatically."""
    from .detectors import is_nextjs_distribution

    if is_nextjs_distribution(project_dir):
        return write_nextjs_dist_launcher(project_dir, port)
    return write_nextjs_dev_launcher(project_dir, port)


def node_tool_path_entries() -> list[str]:
    """Directories that usually contain pm2.cmd / node.exe (GUI apps often lack these on PATH)."""
    entries: list[str] = []
    seen: set[str] = set()

    def add(path: Path | str | None) -> None:
        if not path:
            return
        text = str(path).strip().strip('"')
        if not text or text in seen:
            return
        seen.add(text)
        entries.append(text)

    for key in ("PATH", "Path"):
        for part in (os.environ.get(key) or "").split(os.pathsep):
            add(part)

    appdata = os.environ.get("APPDATA")
    localappdata = os.environ.get("LOCALAPPDATA")
    if appdata:
        add(Path(appdata) / "npm")
    if localappdata:
        add(Path(localappdata) / "npm")

    for env_key in ("ProgramFiles", "ProgramFiles(x86)"):
        base = os.environ.get(env_key)
        if base:
            add(Path(base) / "nodejs")

    return entries


def find_python() -> str | None:
    """Resolve python.exe for PM2 apps that use interpreter: python."""
    search_path = os.pathsep.join(node_tool_path_entries())
    for name in ("python.exe", "python"):
        found = shutil.which(name, path=search_path) if search_path else shutil.which(name)
        if found:
            return found
    for env_key in ("LOCALAPPDATA", "ProgramFiles"):
        base = os.environ.get(env_key)
        if not base:
            continue
        for sub in (
            Path(base) / "Programs" / "Python" / "Python311" / "python.exe",
            Path(base) / "Programs" / "Python" / "Python312" / "python.exe",
            Path(base) / "Programs" / "Python" / "Python313" / "python.exe",
        ):
            if sub.is_file():
                return str(sub)
    return None


def find_pm2() -> str | None:
    """Resolve pm2 executable (pm2.cmd on Windows)."""
    search_path = os.pathsep.join(node_tool_path_entries())
    for name in ("pm2.cmd", "pm2.exe", "pm2"):
        found = shutil.which(name, path=search_path) if search_path else shutil.which(name)
        if found:
            return found
    for directory in node_tool_path_entries():
        for name in ("pm2.cmd", "pm2.exe", "pm2"):
            candidate = Path(directory) / name
            if candidate.is_file():
                return str(candidate)
    return None


def augment_path_env(env: dict[str, str] | None = None) -> dict[str, str]:
    """Ensure npm global bin, Node.js, and Python are on PATH for child processes."""
    merged = dict(env or os.environ)
    extra = list(node_tool_path_entries())
    py = find_python()
    if py:
        extra.insert(0, str(Path(py).parent))
    if not extra:
        return merged
    current = merged.get("PATH") or merged.get("Path") or ""
    prefix = os.pathsep.join(p for p in extra if p and p not in current)
    if prefix:
        merged["PATH"] = f"{prefix}{os.pathsep}{current}" if current else prefix
    return merged


def pm2_command(*args: str, env: dict[str, str] | None = None) -> list[str]:
    """Argv to run pm2 (full path on Windows when PATH is minimal)."""
    pm2 = find_pm2() or "pm2"
    if sys.platform == "win32":
        return ["cmd", "/c", pm2, *args]
    return [pm2, *args]


def _patch_ecosystem_ports(
    ecosystem_text: str,
    *,
    server_port: int,
    vault_port: int | None,
    detected_server: int,
    detected_vault: int | None,
) -> str:
    """Rewrite PORT / localhost / VAULT_PORT values for MultiServer-assigned ports."""
    port_map: dict[int, int] = {}
    if detected_server and detected_server != server_port:
        port_map[detected_server] = server_port
    if vault_port is not None and detected_vault and detected_vault != vault_port:
        port_map[detected_vault] = vault_port

    text = ecosystem_text
    for old, new in port_map.items():
        text = re.sub(rf"PORT:\s*{old}\b", f"PORT: {new}", text)
        text = re.sub(
            rf"VAULT_PORT:\s*{old}\b", f"VAULT_PORT: {new}", text, flags=re.IGNORECASE
        )
        text = re.sub(
            rf"localhost:{old}\b", f"localhost:{new}", text, flags=re.IGNORECASE
        )
        text = re.sub(
            rf"http://localhost:{old}\b",
            f"http://localhost:{new}",
            text,
            flags=re.IGNORECASE,
        )
    return text


def _pm2_node_app_names(ecosystem_text: str) -> list[str]:
    """Apps that are not Python — required for a successful demo start."""
    names: list[str] = []
    for match in re.finditer(r"name:\s*['\"]([^'\"]+)['\"]", ecosystem_text):
        chunk = ecosystem_text[match.start() : match.start() + 1200]
        if re.search(r"interpreter:\s*['\"]python['\"]", chunk, re.IGNORECASE):
            continue
        if re.search(r"interpreter:\s*['\"][^'\"]*python[^'\"]*['\"]", chunk, re.IGNORECASE):
            continue
        if re.search(r"script:\s*['\"][^'\"]+\.py['\"]", chunk, re.IGNORECASE):
            continue
        names.append(match.group(1))
    return names


def _patch_pm2_for_multiserver_demo(ecosystem_text: str, server_port: int) -> str:
    """Law Firm on MultiServer: avoid HSTS-on-HTTP, fix CORS for assigned port."""
    text = ecosystem_text.replace("BEHIND_PROXY: 'true'", "BEHIND_PROXY: 'false'")
    text = text.replace('BEHIND_PROXY: "true"', 'BEHIND_PROXY: "false"')
    text = text.replace("BEHIND_CLOUDFLARE: 'true'", "BEHIND_CLOUDFLARE: 'false'")
    text = text.replace('BEHIND_CLOUDFLARE: "true"', 'BEHIND_CLOUDFLARE: "false"')
    cors = (
        f"http://localhost:{server_port},http://127.0.0.1:{server_port},"
        "https://www.computerdynamicstt.com,http://www.computerdynamicstt.com"
    )
    inject = (
        f"\n      CLIENT_URL: 'http://localhost:{server_port}',\n"
        f"      CORS_ORIGINS: '{cors}',\n"
    )

    def add_env(match: re.Match[str]) -> str:
        return match.group(1) + inject

    return re.sub(
        r"(name: 'ms-[^']+-zenlaw-server'[\s\S]*?PORT: \d+,)",
        add_env,
        text,
    )


def _patch_lawfirm_html_assets(html: str) -> str:
    """Use relative Vite asset paths (JS base-tag injection runs too late in the parser)."""
    marker = "multiserver-demo-patch"
    html = re.sub(
        rf"<!-- {marker} -->[\s\S]*?</script>\s*",
        f"<!-- {marker}: relative assets -->\n",
        html,
        count=1,
    )
    if marker not in html:
        html = html.replace("<head>", f"<head>\n<!-- {marker}: relative assets -->\n", 1)
    html = html.replace('src="/index.', 'src="./index.')
    html = html.replace('href="/index.', 'href="./index.')
    html = html.replace('href="/vite.svg"', 'href="./vite.svg"')
    return html


def _run_lawfirm_router_patch(project_dir: Path) -> None:
    """Ensure React Router basename works under /demo/<slug>/."""
    import subprocess

    script = Path(__file__).resolve().parents[1] / "scripts" / "patch-lawfirm-router.js"
    dist = project_dir / "client" / "dist"
    if not script.is_file() or not dist.is_dir():
        return
    node = shutil.which("node") or shutil.which("node.exe")
    if not node:
        return
    for js_path in dist.glob("index.*.js"):
        subprocess.run(
            [node, str(script), str(js_path)],
            check=False,
            capture_output=True,
        )


def patch_lawfirm_client_for_multiserver(project_dir: Path) -> None:
    """Fix API base URL and /demo/<slug>/ asset paths in the built client."""
    dist = project_dir / "client" / "dist"
    if not dist.is_dir():
        return

    html_path = dist / "index.html"
    if html_path.is_file():
        original = html_path.read_text(encoding="utf-8")
        patched = _patch_lawfirm_html_assets(original)
        if patched != original:
            html_path.write_text(patched, encoding="utf-8")

    api_broken = re.compile(
        r'"localhost"===e\|\|"127\.0\.0\.1"===e\?.+?/api`.+?/api`'
    )
    for js_path in dist.glob("index.*.js"):
        text = js_path.read_text(encoding="utf-8")
        original = text

        api_original = (
            '"localhost"===e||"127.0.0.1"===e?'
            '${"undefined"!=typeof window?window.location.origin:"http://localhost:5002"}/api'
            ':"https://zenlaw.online/api"'
        )
        api_patched = (
            '`${"undefined"!=typeof window?((()=>{const m=location.pathname.match(/^\\/demo\\/[^/]+/);'
            'return location.origin+(m?m[0]:"");})()):""}/api`'
        )
        if api_patched not in text:
            if api_original in text:
                text = text.replace(api_original, api_patched)
            elif api_broken.search(text):
                text = api_broken.sub(api_patched, text, count=1)

        if text != original:
            js_path.write_text(text, encoding="utf-8")

    _run_lawfirm_router_patch(project_dir)

    server_index = project_dir / "server" / "dist" / "index.js"
    if server_index.is_file():
        text = server_index.read_text(encoding="utf-8")
        csp_old = (
            "script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; "
            "img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https: http:;"
        )
        csp_new = (
            "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://static.cloudflareinsights.com; "
            "style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; "
            "connect-src 'self' https: http: https://cloudflareinsights.com;"
        )
        if csp_old in text and csp_new not in text:
            server_index.write_text(text.replace(csp_old, csp_new), encoding="utf-8")


def _prefix_pm2_app_names(ecosystem_text: str, prefix: str) -> str:
    """Prefix PM2 app names so multiple demos do not collide in one pm2 daemon."""

    def repl(match: re.Match[str]) -> str:
        quote = match.group(1)
        name = match.group(2)
        if name.startswith(prefix):
            return match.group(0)
        return f"name: {quote}{prefix}{name}{quote}"

    return re.sub(
        r"name:\s*(['\"])([^'\"]+)\1",
        repl,
        ecosystem_text,
    )


def write_pm2_launcher(
    project_dir: Path,
    system_id: str,
    server_port: int,
    vault_port: int | None,
    *,
    detected_server: int | None = None,
    detected_vault: int | None = None,
) -> tuple[Path, list[str]]:
    """
    Generate .multiserver/ecosystem.config.js (patched ports + unique app names) and launch.bat.
    Returns (launch.bat path, list of prefixed PM2 app names for stop/delete).
    """
    from .detectors import detect_pm2_ports, find_ecosystem_config

    project_dir = project_dir.resolve()
    source = find_ecosystem_config(project_dir)
    if not source:
        raise FileNotFoundError(f"No ecosystem.config.js in {project_dir}")

    detected = detect_pm2_ports(project_dir)
    detected_server = detected_server or int(detected.get("detected_server") or server_port)
    detected_vault = detected_vault if detected_vault is not None else detected.get("detected_vault")
    if vault_port is None and detected_vault:
        vault_port = int(detected_vault)

    prefix = f"ms-{system_id[:8]}-"
    text = source.read_text(encoding="utf-8", errors="ignore")
    text = _patch_ecosystem_ports(
        text,
        server_port=server_port,
        vault_port=vault_port,
        detected_server=detected_server,
        detected_vault=int(detected_vault) if detected_vault else None,
    )
    text = _prefix_pm2_app_names(text, prefix)
    text = _patch_pm2_for_multiserver_demo(text, server_port)

    py_exe = find_python()
    if py_exe:
        py_for_js = py_exe.replace("\\", "/")
        text = re.sub(
            r"interpreter:\s*['\"]python['\"]",
            f'interpreter: "{py_for_js}"',
            text,
            flags=re.IGNORECASE,
        )

    ms_dir = project_dir / ".multiserver"
    ms_dir.mkdir(exist_ok=True)
    eco_out = ms_dir / "ecosystem.config.js"
    eco_out.write_text(text, encoding="utf-8")
    patch_lawfirm_client_for_multiserver(project_dir)

    all_app_names = re.findall(r"name:\s*['\"]([^'\"]+)['\"]", text)
    start_app_names = _pm2_node_app_names(text) or all_app_names

    names_file = ms_dir / "pm2-app-names.json"
    names_file.write_text(json.dumps(all_app_names, indent=2), encoding="utf-8")

    delete_cmds = " ".join(f'"{n}"' for n in all_app_names)
    start_only = ",".join(start_app_names)
    optional_apps = [n for n in all_app_names if n not in start_app_names]
    optional_start_lines = "".join(
        f'call "%PM2%" start "{eco_out}" --only "{name}" 2>nul\r\n'
        for name in optional_apps
    )
    pm2_exe = find_pm2()
    path_entries = list(node_tool_path_entries())
    if py_exe:
        path_entries.insert(0, str(Path(py_exe).parent))
    path_append = ";".join(path_entries)

    launch = ms_dir / "launch.bat"
    if not pm2_exe:
        launch.write_text(
            f"@echo off\r\n"
            f"chcp 65001 >nul\r\n"
            f'cd /d "{project_dir}"\r\n'
            f"echo ERROR: PM2 was not found.\r\n"
            f"echo Install: npm install -g pm2\r\n"
            f"echo Then restart MultiServer.\r\n"
            f"exit /b 1\r\n",
            encoding="utf-8",
        )
        return launch, all_app_names

    launch.write_text(
        f"@echo off\r\n"
        f"chcp 65001 >nul\r\n"
        f'cd /d "{project_dir}"\r\n'
        f'set "PATH={path_append};%PATH%"\r\n'
        f'set "PM2={pm2_exe}"\r\n'
        f"echo Using PM2: %PM2%\r\n"
        f"echo Stopping previous MultiServer PM2 apps for this demo...\r\n"
        f'call "%PM2%" delete {delete_cmds} 2>nul\r\n'
        f'call "%PM2%" start "{eco_out}" --only "{start_only}"\r\n'
        f"if errorlevel 1 (\r\n"
        f"  echo PM2 start failed. Check server dependencies: cd server ^&^& npm install --omit=dev\r\n"
        f"  call \"%PM2%\" logs --lines 30\r\n"
        f"  exit /b 1\r\n"
        f")\r\n"
        f"{optional_start_lines}"
        f'call "%PM2%" status\r\n'
        f"echo PM2 apps started. Close this window to stop (MultiServer will delete apps on Stop).\r\n"
        f":wait\r\n"
        f"timeout /t 3600 /nobreak >nul\r\n"
        f"goto wait\r\n",
        encoding="utf-8",
    )
    return launch, all_app_names


def pm2_stop_apps(project_dir: Path) -> None:
    """Delete PM2 apps created by write_pm2_launcher."""
    names_file = project_dir / ".multiserver" / "pm2-app-names.json"
    if not names_file.is_file():
        return
    try:
        app_names = json.loads(names_file.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return
    if not app_names:
        return
    cmd = pm2_command("delete", *app_names)
    subprocess_run_quiet(cmd, env=augment_path_env())


def subprocess_run_quiet(
    command: list[str], *, env: dict[str, str] | None = None
) -> None:
    import subprocess

    flags = getattr(subprocess, "CREATE_NO_WINDOW", 0) if sys.platform == "win32" else 0
    subprocess.run(
        command,
        capture_output=True,
        check=False,
        creationflags=flags,
        env=augment_path_env(env),
    )
