export type MiniCompanionKind = 'thought' | 'request' | 'assistance' | 'growth' | string;

export type MiniChatEntry = {
  role: string;
  content: string;
  created_at?: string | null;
  kind?: MiniCompanionKind;
  read?: boolean;
  fingerprint?: string;
};

export type MiniGrowthPayload = {
  narrative?: string;
  maturity?: string;
  totals?: Record<string, number>;
  deltas?: Record<string, number>;
  companion_activity?: Record<string, number>;
};

export function companionKindLabel(kind?: MiniCompanionKind): string {
  switch (kind) {
    case 'thought':
      return 'Mini · thinking';
    case 'request':
      return 'Mini · request';
    case 'assistance':
      return 'Mini · assistance';
    case 'growth':
      return 'Mini · growth';
    default:
      return 'Mini';
  }
}

export function companionBubbleClass(role: string, kind?: MiniCompanionKind): string {
  if (role === 'companion') {
    if (kind === 'request') {
      return 'border border-amber-200 bg-amber-50 text-amber-950';
    }
    if (kind === 'assistance') {
      return 'border border-emerald-200 bg-emerald-50 text-emerald-950';
    }
    if (kind === 'growth') {
      return 'border border-violet-200 bg-violet-50 text-violet-950';
    }
    return 'border border-fuchsia-200 bg-fuchsia-50 text-fuchsia-950';
  }
  if (role === 'assistant') {
    return 'bg-white text-slate-800 shadow-sm';
  }
  if (role === 'system') {
    return 'border border-slate-200 bg-slate-100 text-slate-700';
  }
  return 'bg-sky-100 text-sky-950';
}

export function companionKindBadgeClass(kind?: MiniCompanionKind): string {
  if (kind === 'request') return 'bg-amber-100 text-amber-800';
  if (kind === 'assistance') return 'bg-emerald-100 text-emerald-800';
  if (kind === 'growth') return 'bg-violet-100 text-violet-800';
  return 'bg-fuchsia-100 text-fuchsia-800';
}

export type MiniActivityHeadlineInput = {
  summary?: string;
  status?: string;
  current_goal?: string;
  provider_label?: string;
  pending_goals?: number;
  pending_approvals?: number;
  execution_status?: string;
};

const MINI_INTERNAL_ACTIVITY_MARKERS = [
  'Generated by heuristic brain',
  'Memory hint:',
  'integrity=',
  'capability=',
  'focus=',
  'Reusable skill formed',
  'Wrote note:',
] as const;

/** Raw cycle logs from Mini — belong in the companion feed, not the portal header. */
export function isMiniInternalActivityDump(text: string): boolean {
  const trimmed = text.trim();
  if (!trimmed) return false;
  if (trimmed.length > 240) return true;
  if (trimmed.includes('\n')) return true;
  if ((trimmed.match(/\bGoal:/g) || []).length >= 2) return true;
  if ((trimmed.match(/Memory hint:/g) || []).length >= 2) return true;
  if ((trimmed.match(/State:/g) || []).length >= 2) return true;
  return MINI_INTERNAL_ACTIVITY_MARKERS.some((marker) => trimmed.includes(marker));
}

export function formatMiniActivityHeadline(
  activity: MiniActivityHeadlineInput | undefined,
  options?: { hydrationLoading?: boolean },
): string {
  const fallback = 'Mini assistant dashboard — live data from your docked Mini instance.';
  if (options?.hydrationLoading) {
    return 'Loading live status from your docked Mini instance…';
  }
  if (!activity) return fallback;

  const summary = activity.summary?.trim();
  if (summary && !isMiniInternalActivityDump(summary)) {
    return summary;
  }

  const parts: string[] = [];
  const status = activity.status?.trim();
  if (status && status !== 'ready') {
    parts.push(`Status: ${status}`);
  }
  const goal = activity.current_goal?.trim();
  if (goal && goal !== 'No queued goal') {
    parts.push(`Working on: ${goal}`);
  }
  const provider = activity.provider_label?.trim();
  if (provider) {
    parts.push(provider);
  }
  if (typeof activity.pending_approvals === 'number' && activity.pending_approvals > 0) {
    parts.push(
      `${activity.pending_approvals} approval${activity.pending_approvals === 1 ? '' : 's'} waiting`,
    );
  }

  return parts.length > 0 ? parts.join(' · ') : fallback;
}
